import { Level, MapNode } from './types';

export const LEVELS: Level[] = [
  {
    id: 'prehistoric-culture',
    title: '銀河神話與史前文化',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwU5zC5nyK9nFDzzjLPFdcb-BodfDXF9bL7UYruPNO9gyhdd1oLgOlPcxol1AJ7Kw4OB2Fm19envshR7teQsE7qYbO-vKNmBG4DHtr1F1XwE3x_FEjIUPQtZtM3oMQd94BYTBfmI6xxY5LA_8ZmcjQUio1_1iGmluIyGd6wNymvoeAWAG7hRvRL0u2rBNZbBR6ZIXQfuD6-_vevLwrizdyuIVpuFii-LsvhyYMgWO2zAHtuxnI7xYyuv5H4fSVdZ6DFZa71qoIB64',
    questions: [
      {
        id: 'pc-1',
        text: '在北美拉科塔（Lakota）族的神話中，銀河被賦予了什麼樣的稱呼與意義？',
        source: '拉科塔族人',
        options: [
          { id: 'A', text: '世界樹的枝幹' },
          { id: 'B', text: '天上的恆河' },
          { id: 'C', text: '冬之街' },
          { id: 'D', text: '靈魂之路' },
        ],
        correctAnswer: 'D',
      },
      {
        id: 'pc-2',
        text: '澳洲原住民觀測銀河時，將其中的「暗雲」區域想像成什麼動物？',
        source: '澳洲原住民',
        options: [
          { id: 'A', text: '鴯鶓' },
          { id: 'B', text: '袋鼠' },
          { id: 'C', text: '獵鷹' },
          { id: 'D', text: '無尾熊' },
        ],
        correctAnswer: 'A',
      },
      {
        id: 'pc-3',
        text: '桑（Saan）族人利用銀河來傳授什麼樣的族群記憶？',
        source: '非洲原住民',
        options: [
          { id: 'A', text: '農業耕種的時間表' },
          { id: 'B', text: '狩獵知識與自然倫理' },
          { id: 'C', text: '建造金字塔的工程圖示' },
          { id: 'D', text: '海上航行的導航技術' },
        ],
        correctAnswer: 'B',
      },
    ],
  },
  {
    id: 'literature-art',
    title: '文學與藝術的銀河',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDehyuVxTWy_B3wLEXqAQc-T5ZGrJPiZ2IpTlOg1mIXvvj6jENDyB1ieALRUDTb2BPrBY3tf-OEMJDRq_FzNZwk7KNVHSGyIz6yjhPBY46S2yve9yz5Kj5CnIeTi3mo2qXDirENRE_FFEKBZbZMb-2af1XmNmw0R6vps4moS02TUquslqb7TnXkS8lftHfamPHipC5jWCmE-nzFRN844m1l4q3mkUAkxp6Chttulpl2O1_UiqUXLJ3TORRq7247dquH3XHbsrEt9MQ',
    questions: [
      {
        id: 'la-1',
        text: '銀河在宮澤賢治的作品《銀河鐵道之夜》中，主角最終發現銀河鐵道的真相與什麼有關？',
        source: '《銀河鐵道之夜》宮澤賢治',
        options: [
          { id: 'A', text: '星際旅行的航線' },
          { id: 'B', text: '外星文明的交通工具' },
          { id: 'C', text: '引領靈魂的旅程' },
          { id: 'D', text: '科學家的夢境' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 'la-2',
        text: '在梵谷的名畫《星夜》中，天空那些強烈的流動線條，可能受到了什麼科學概念的啟發？',
        source: '《星夜》梵谷',
        options: [
          { id: 'A', text: '彗星經過的尾跡' },
          { id: 'B', text: '螺旋星系的樣貌' },
          { id: 'C', text: '太陽風的流動' },
          { id: 'D', text: '黑洞的事件視界' },
        ],
        correctAnswer: 'B',
      },
    ],
  },
  {
    id: 'myths-legends',
    title: '東西方的銀河傳說',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlldi69nLFXJ_cpgP3-IiZugPlpjRcs2EFteiXQx9rRXFOgyWRZ3HHxuOSyRhfqleUlBAqR6xG5SMq3xxDjeDYPPCNb8Bv23-_nYAridGBi0y6RBzwKrYf5obf5dZ-4nqEH5lXh25CXHY1KZYnubu1RUb165LOwRWDKB3S1D0RIvZEFuEBxFmRYNsVNB4MrQAFiRIuIHKTiQuqp51NSeXv-ndAv7lGPkSamDA7gPXkQcJr9ewPL4GUBQgoyhK3SE-6xyEKdnJ6bio',
    questions: [
      {
        id: 'ml-1',
        category: 'Greek Culture',
        text: '古希臘哲學家亞里斯多德（Aristotle）如何以自然哲學解釋銀河的成因？',
        source: '希臘文化',
        options: [
          { id: 'A', text: '天界神聖的乳汁' },
          { id: 'B', text: '大氣層上方蒸氣燃燒形成' },
          { id: 'C', text: '恆星密集排列的光芒' },
          { id: 'D', text: '宇宙早期的塵埃帶' },
        ],
        correctAnswer: 'B',
      },
      {
        id: 'ml-2',
        category: 'Norse Mythology',
        text: '瑞典語將銀河稱為「冬之街（Vintergatan）」，這在北歐神話中代表什麼？',
        source: '北歐神話',
        options: [
          { id: 'A', text: '霜巨人的居所' },
          { id: 'B', text: '封印邪惡巨狼的鎖鏈' },
          { id: 'C', text: '引領陣亡戰士前往英靈殿的道路' },
          { id: 'D', text: '眾神舉行宴會的地方' },
        ],
        correctAnswer: 'C',
      },
    ],
  },
  {
    id: 'galaxy-heart',
    title: '銀河之心',
    heroImage: 'https://lh3.googleusercontent.com/aida/ADBb0uiPoCWSLsfnNtE-BbSznrA5buczIBsf_RpGZbtkPI_ybzmVyt-1PvOI6fYRft4WvSEtz4vglTyi20FnyUV50YKoIrwNJ72Pt8fE1p2kpz2Ejg3aZZZ5Pther-y9R4n8rx-PQOQHRILlr23IHp5zkKSDORyjIF9Bc38x2rkpLnMBrtgunA3Q8w_Q4Xg4gSRNyy7d_uwLpiXD9qMvIXrPEOKYZzT3BQEUKhtkMfsj2HwBfdkD5KpeElzt9TAxTjyGgXlb-a-oB-QS5g',
    questions: [
      {
        id: 'gh-1',
        text: '太陽系位於銀河系的哪一個結構上？',
        source: '銀河中的太陽系',
        options: [
          { id: 'A', text: '銀河核球' },
          { id: 'B', text: '獵戶座旋臂' },
          { id: 'C', text: '銀暈' },
          { id: 'D', text: '英仙座旋臂' },
        ],
        correctAnswer: 'B',
      },
      {
        id: 'gh-2',
        text: '太陽系繞行銀河系中心一週大約需要多少年？',
        source: '銀河中的太陽系',
        options: [
          { id: 'A', text: '1千萬年' },
          { id: 'B', text: '1百萬年' },
          { id: 'C', text: '130億年' },
          { id: 'D', text: '2億5千萬年' },
        ],
        correctAnswer: 'D',
      },
      {
        id: 'gh-3',
        text: '銀河系中心的超大質量黑洞「人馬座A*」的質量大約是太陽的多少倍？',
        source: '銀河系的運動',
        options: [
          { id: 'A', text: '1000億倍' },
          { id: 'B', text: '100倍' },
          { id: 'C', text: '430萬倍' },
          { id: 'D', text: '6000億倍' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 'gh-4',
        text: '關於銀河系的質量分佈，科學家薇拉．魯賓（Vera Rubin）發現了什麼矛盾現象？',
        source: '看不見的暗物質',
        options: [
          { id: 'A', text: '可見物質的引力不足以維持盤面旋轉速度' },
          { id: 'B', text: '核心黑洞不斷吞噬周圍恆星' },
          { id: 'C', text: '恆星數量遠低於先前的估計值' },
          { id: 'D', text: '銀河系正以超光速向外擴張' },
        ],
        correctAnswer: 'A',
      },
      {
        id: 'gh-5',
        text: '銀河系中除了發光的恆星與氣體，還有一種像「巨大球體」包裹著整個星系的隱形物質，它是什麼？',
        source: '看不見的暗物質',
        options: [
          { id: 'A', text: '暗物質' },
          { id: 'B', text: '星際塵埃雲' },
          { id: 'C', text: '反物質' },
          { id: 'D', text: '宇宙微波背景' },
        ],
        correctAnswer: 'A',
      },
    ],
  },
  {
    id: 'seasons',
    title: '銀河的四季風貌',
    heroImage: 'https://lh3.googleusercontent.com/aida/ADBb0ujYtIOyCEwTC-GR6D-krJTCrYVYDmjQhVAKlg6p1oOJHNF4FqO4PMFnwn6uskoXwB5xZ3D9nU3NTqQpVt4uYMC9H3WG9YV-BpLp7WTXYlW0bJHX71senha0ms5hA70rt4Yd2Obd7IPM0g6hWN6omT8nImb7_q9Xe0hWCHtSz091aPgcZI5yQZKrNFM8hxJvl3X0ZKCIvtM9zMLWTUV3ppJYxUHCtvgQ42xAQ792WzrKJHff_A8-DOXrdeoBc2Xjmzr9hFmpVetyqA',
    missionObjective: 'Orbital Surveillance: Seasonal Drift',
    questions: [
      {
        id: 's-1',
        text: '在春季的臺灣夜空，雖然銀河本體難以看見，但在哪個星座方向可以觀測到眾多的遙遠星系？',
        source: '銀河的四季風貌',
        options: [
          { id: 'A', text: '獵戶座' },
          { id: 'B', text: '天蠍座' },
          { id: 'C', text: '獅子座與室女座' },
          { id: 'D', text: '仙后座' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 's-2',
        text: '夏季銀河中最明亮的區域位在哪個星座方向？此處也隱藏著超大質量黑洞。',
        source: '銀河的四季風貌',
        options: [
          { id: 'A', text: '人馬座' },
          { id: 'B', text: '天鵝座' },
          { id: 'C', text: '天鷹座' },
          { id: 'D', text: '天琴座' },
        ],
        correctAnswer: 'A',
      },
    ],
  },
  {
    id: 'gaia-mission',
    title: '蓋亞任務',
    heroImage: 'https://lh3.googleusercontent.com/aida/ADBb0uhGV_1roreew1cy7zxpzwoC5DcfTr8qHYlCIIyyNNMoRHZn94_xiwz2Jouo4K3XGgDb6gq1sDx07N21tcRxHoukFo-ptUpWNrZFsrkMSddOfOJXKd6vSqa8g9czAE4pRxtjLktAcZJzWFg5zZbsr2HkjCmRRXPwz9ZqAJmsJa672nPHXxTgF0mVc4ybvaVWRzfXCygnVBM8B2cSwA-7h-lVooDAH-4x_PRHdjqHdb_9_5rrLnqFb2_KjYsbDgbDgsKhmPHuiUfeaQ',
    questions: [
      {
        id: 'gm-1',
        text: '蓋亞（Gaia）望遠鏡目前位於何處進行觀測任務？',
        source: '任務的時間與地點',
        options: [
          { id: 'A', text: '月球背面' },
          { id: 'B', text: '火星軌道' },
          { id: 'C', text: '地球同步軌道' },
          { id: 'D', text: '第二拉格朗日點（L2）附近' },
        ],
        correctAnswer: 'D',
      },
      {
        id: 'gm-2',
        text: '蓋亞任務目前已發布多個版本的資料，預計哪一年會發布包含10年完整分析資料的DR5版本？',
        source: '蓋亞資料發表',
        options: [
          { id: 'A', text: '2013年' },
          { id: 'B', text: '2030年' },
          { id: 'C', text: '2020年' },
          { id: 'D', text: '2026年' },
        ],
        correctAnswer: 'B',
      },
      {
        id: 'gm-3',
        text: '蓋亞任務中發現的「蓋亞—恩克拉多斯（Gaia-Enceladus）」是指什麼？',
        source: '銀河考古學',
        options: [
          { id: 'A', text: '銀河系中最高溫的恆星流' },
          { id: 'B', text: '一種新型態的暗物質粒子' },
          { id: 'C', text: '100億年前與銀河系合併的古老星系遺骸' },
          { id: 'D', text: '一顆位於銀河中心的新行星' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 'gm-4',
        text: '在銀河中心發現的兩股古老恆星流「濕婆（Shiva）」與「沙克蒂（Shakti）」，其特點為何？',
        source: '發現古老恆星流',
        options: [
          { id: 'A', text: '見證了銀河系盤面形成前的初期樣貌' },
          { id: 'B', text: '是由仙女座星系噴射而出的恆星' },
          { id: 'C', text: '正以超光速遠離銀河中心' },
          { id: 'D', text: '含有極豐富的金屬元素' },
        ],
        correctAnswer: 'A',
      },
    ],
  },
  {
    id: 'future-past',
    title: '銀河的過去與未來',
    heroImage: 'https://lh3.googleusercontent.com/aida/ADBb0ujv1swGYxFwh2aaLlNX0yGYtNbvDImyL4CReIxBG035cPslNopsB1hHAQUszaOz2ntMbJftIICutmqWWbezloPb2ikQtSSjepAzmzlghxj564xZSyw46X2R9Hz3ujw0CjZu_rDRPkAe3VX71G_bc9k-K3CP3VShn3mu52XasyAkCJDt21PSOLtmj1BLwOLRP9IiXknUf8Ft3Nc4lY5q-eUEWncR-JMveB3bYPCGfG9R025kOgQXOsiSRcIzfGm5POM_KcZRHviT',
    questions: [
      {
        id: 'fp-1',
        text: '大質量恆星在死亡時發生的哪種天文事件，能為銀河系製造出比鐵更重的元素？',
        source: '宇宙的元素煉金術',
        options: [
          { id: 'A', text: '原恆星塌縮' },
          { id: 'B', text: '超新星爆炸' },
          { id: 'C', text: '紅巨星膨脹' },
          { id: 'D', text: '黑洞吸積' },
        ],
        correctAnswer: 'B',
      },
      {
        id: 'fp-2',
        text: '根據目前的觀測，仙女座星系正以大約多少速度向銀河系接近？',
        source: '跨越億萬年的星際華爾滋',
        options: [
          { id: 'A', text: '每秒600公里' },
          { id: 'B', text: '每秒110公里' },
          { id: 'C', text: '時速8400萬公里' },
          { id: 'D', text: '每秒30萬公里' },
        ],
        correctAnswer: 'B',
      },
      {
        id: 'fp-3',
        text: '當數十億年後銀河系與仙女座星系正式碰撞時，最不可能發生的現象是？',
        source: '雲氣擠壓與新星爆發',
        options: [
          { id: 'A', text: '觸發大規模的恆星誕生潮' },
          { id: 'B', text: '形成一個巨大的橢圓星系' },
          { id: 'C', text: '星系旋臂結構消失崩解' },
          { id: 'D', text: '恆星與恆星之間發生直接對撞' },
        ],
        correctAnswer: 'D',
      },
      {
        id: 'fp-4',
        text: '銀河系與仙女座星系合併後的最終終點站，預期會形成哪種形狀的星系？',
        source: '旋臂重組與消逝',
        options: [
          { id: 'A', text: '不規則星系' },
          { id: 'B', text: '棒狀星系' },
          { id: 'C', text: '橢圓星系' },
          { id: 'D', text: '更大的螺旋星系' },
        ],
        correctAnswer: 'C',
      },
    ],
  },
  {
    id: 'webb-telescope',
    title: '韋伯望遠鏡',
    heroImage: 'https://lh3.googleusercontent.com/aida/ADBb0uizEy3_3dSzLp2yIom2L0KF4xb_6z1Z4yeyNz31smXymQIAzS5-Dg14pvBXEt9ENZDrTwObevfrxAG5Qpv37BTa5M6bkik0cdCMK6Mo6ePDKYvAZKS0pddTZfBk3SCOUoonw8D2goiR-fLurDG65MF6yXw_Om5vbRi6J_Ai300vcLHeuzHEexwi2bSp2vJI1zLRFrIDchHhVKA4NyKtF1WLm7nUjkY5sd9aA6gC0vsoAFk6l5Ca3o9KQlQDTUar-78k79Fw4iDPpg',
    questions: [
      {
        id: 'wt-1',
        text: '韋伯太空望遠鏡（JWST）主要利用哪種波段來穿透星際塵埃？',
        source: '穿透塵埃：直擊銀河系的心臟',
        options: [
          { id: 'A', text: 'X射線' },
          { id: 'B', text: '紫外光' },
          { id: 'C', text: '可見光' },
          { id: 'D', text: '紅外線' },
        ],
        correctAnswer: 'D',
      },
      {
        id: 'wt-2',
        text: '韋伯望遠鏡拍攝的「蜘蛛星雲（Tarantula Nebula）」位於哪個銀河系鄰近的天體中？',
        source: '星系產房：恆星誕生的生命搖籃',
        options: [
          { id: 'A', text: '仙女座星系' },
          { id: 'B', text: '草帽星系' },
          { id: 'C', text: '獵戶座大星雲' },
          { id: 'D', text: '大麥哲倫星系' },
        ],
        correctAnswer: 'D',
      },
    ],
  },
  {
    id: 'black-hole',
    title: '超大質量黑洞',
    heroImage: 'https://lh3.googleusercontent.com/aida/ADBb0ugjEOjI-I0PclE-Jtqq_lCc3wRTOhkkFo3WrTxj6QKwcxOg-06BuDiwVrZVXrRk9tDd-ot8rla_EUNWLl1PLx4q7DSc3HbvfnOjBtoO1PTrjd-ZlyoryV-TCvGKOszvOv6QpO9OT6HNK7ELTQIktKA8WfOHC5WiOc_ut7yK9hbVWhVFP-Xuto_usD-0RWUrCFGjXYKQqTBHXcnaKWgeyiyU5XSy5UGO-rdpfXZ0pwrSP6WuuYWkfPNYL1iViyNtuhzFYYQtkL8EJg',
    missionObjective: 'Deep Space Expedition MISSION 04',
    questions: [
      {
        id: 'bh-1',
        text: '關於星系演化的「謎團」，天文學家目前仍無法完全解答下列哪一項？',
        source: '超大質量黑洞的本質',
        options: [
          { id: 'A', text: '仙女座星系是否正在接近' },
          { id: 'B', text: '月球是如何形成的' },
          { id: 'C', text: '恆星內部是否進行核融合' },
          { id: 'D', text: '最初的「種子黑洞」來源為何' },
        ],
        correctAnswer: 'D',
      },
    ],
  },
  {
    id: 'conditions',
    title: '適合觀賞銀河的條件',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDC-iWXWb2JgY28ogq-MEiclyayY6nMDWpK0ZL8mzhi7DEeeq_vG_Qq4YU5ruqy4J5PPb_JtOWvlaFOFDc57cxi7J4ZvnYA1dpPihwbaUic7V3A4WxqWPyvTsbeFk0tB-YNzxLTXordaVmxPW-yOqqznClbHl_boboD1v_eyyC9mwGmXjS83xVFmlY-Rss2fBSGRTa9n-pODY_pMFjcyj5tPCMKXsfadpPU2eTYmUEdE4FMrD6mCo6IXEbCgx0IDinsF_Dpn46oms',
    questions: [
      {
        id: 'c-1',
        text: '在冬季觀看銀河，會發現其光澤較為淡淡白光，這是因為我們正望向銀河系的哪個方向？',
        source: '觀賞銀河的季節',
        options: [
          { id: 'A', text: '黑洞的陰影區' },
          { id: 'B', text: '銀河中心' },
          { id: 'C', text: '外圍旋臂區域' },
          { id: 'D', text: '另一個宇宙的邊界' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 'c-2',
        text: '在臺灣觀賞夏季銀河時，若想看到最壯觀的垂直銀河，哪段時間最適合？',
        source: '觀賞銀河的時段',
        options: [
          { id: 'A', text: '九月底的午夜' },
          { id: 'B', text: '三月底的午夜' },
          { id: 'C', text: '六月底至七月初的午夜' },
          { id: 'D', text: '十二月中的午夜' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 'c-3',
        text: '為什麼觀賞銀河除了避開城市光害，還必須選擇「農曆初一」附近的日期？',
        source: '觀賞銀河的條件',
        options: [
          { id: 'A', text: '為了配合地磁場的週期' },
          { id: 'B', text: '避免月光照亮大氣干擾觀測' },
          { id: 'C', text: '防止潮汐力影響望遠鏡穩定度' },
          { id: 'D', text: '初一的星星數量會特別多' },
        ],
        correctAnswer: 'B',
      },
      {
        id: 'c-4',
        text: '合歡山馬雅平台（合歡山主峰步道）之所以著名，是因為它是臺灣哪項認證的地點？',
        source: '臺灣賞銀河地點推薦',
        options: [
          { id: 'A', text: '國家級地質觀測站' },
          { id: 'B', text: '世界自然遺產' },
          { id: 'C', text: '國際暗空公園' },
          { id: 'D', text: '全球最高天文台所在地' },
        ],
        correctAnswer: 'C',
      },
      {
        id: 'c-5',
        text: '位於南美洲智利的阿塔卡馬沙漠（Atacama Desert）為何被譽為「世界之眼」？',
        source: '世界級銀河觀賞點',
        options: [
          { id: 'A', text: '因為那裡有全世界最大的隕石坑' },
          { id: 'B', text: '沙漠地形酷似眼睛的形狀' },
          { id: 'C', text: '是全球唯一可以看到所有88星座的地方' },
          { id: 'D', text: '極乾空氣與極高晴天率吸引眾多頂尖望遠鏡進駐' },
        ],
        correctAnswer: 'D',
      },
    ],
  },
];

export const MAP_NODES: MapNode[] = [
  { id: 'n1', levelId: 'prehistoric-culture', icon: 'history', label: '銀河神話與史前文化', top: '10%', left: '15%' },
  { id: 'n8', levelId: 'webb-telescope', icon: 'eye', label: '韋伯望遠鏡', top: '15%', left: '60%' },
  { id: 'n2', levelId: 'myths-legends', icon: 'book', label: '東西方的銀河傳說', top: '22%', left: '75%' },
  { id: 'n3', levelId: 'literature-art', icon: 'palette', label: '文學與藝術的銀河', top: '38%', left: '48%' },
  { id: 'n4', levelId: 'seasons', icon: 'cloud-sun', label: '銀河的四季風貌', top: '55%', left: '10%' },
  { id: 'n5', levelId: 'galaxy-heart', icon: 'sun', label: '銀河之心', top: '52%', left: '65%' },
  { id: 'n10', levelId: 'conditions', icon: 'mountain', label: '適合觀賞銀河的條件', top: '68%', left: '80%' },
  { id: 'n6', levelId: 'gaia-mission', icon: 'rocket', label: '蓋亞任務', top: '72%', left: '30%' },
  { id: 'n7', levelId: 'future-past', icon: 'clock', label: '銀河的過去與未來', top: '82%', left: '50%' },
  { id: 'n9', levelId: 'black-hole', icon: 'disc', label: '超大質量黑洞', top: '88%', left: '78%' },
];
